theme: jekyll-theme-slate
title: WiFi Duck
description: Open-Source Wireless BadUSB
github:
  repository_url: https://github.com/SpacehuhnTech/WiFiDuck
  zip_url: https://github.com/SpacehuhnTech/WiFiDuck/archive/refs/heads/master.zip
  tar_url: https://github.com/SpacehuhnTech/WiFiDuck/archive/refs/heads/master.tar.gz
